from typing import Dict, List, TypedDict

from talipp.indicators import *
from talipp.ohlcv import OHLCV


class MarketData(TypedDict):
    candle: OHLCV
    AccuDist: AccuDist
    ADX: ADX
    ALMA: ALMA
    AO: AO
    Aroon: Aroon
    ATR: ATR
    BB: BB
    BOP: BOP
    CCI: CCI
    ChaikinOsc: ChaikinOsc
    ChandeKrollStop: ChandeKrollStop
    CHOP: CHOP
    CoppockCurve: CoppockCurve
    DEMA: DEMA
    DonchianChannels: DonchianChannels
    DPO: DPO
    EMA: EMA
    EMV: EMV
    ForceIndex: ForceIndex
    HMA: HMA
    Ichimoku: Ichimoku
    KAMA: KAMA
    KeltnerChannels: KeltnerChannels
    KST: KST
    KVO: KVO
    MACD: MACD
    MassIndex: MassIndex
    McGinleyDynamic: McGinleyDynamic
    MeanDev: MeanDev
    OBV: OBV
    ROC: ROC
    RSI: RSI
    ParabolicSAR: ParabolicSAR
    SFX: SFX
    SMA: SMA
    SMMA: SMMA
    SOBV: SOBV
    STC: STC
    StdDev: StdDev
    Stoch: Stoch
    StochRSI: StochRSI
    SuperTrend: SuperTrend
    T3: T3
    TEMA: TEMA
    TRIX: TRIX
    TSI: TSI
    TTM: TTM
    UO: UO
    VTX: VTX
    VWAP: VWAP
    VWMA: VWMA
    WMA: WMA
    ZLEMA: ZLEMA


class MarketDataList(TypedDict):
    candle: List[OHLCV]
    AccuDist: List[AccuDist]
    ADX: List[ADX]
    ALMA: List[ALMA]
    AO: List[AO]
    Aroon: List[Aroon]
    ATR: List[ATR]
    BB: List[BB]
    BOP: List[BOP]
    CCI: List[CCI]
    ChaikinOsc: List[ChaikinOsc]
    ChandeKrollStop: List[ChandeKrollStop]
    CHOP: List[CHOP]
    CoppockCurve: List[CoppockCurve]
    DEMA: List[DEMA]
    DonchianChannels: List[DonchianChannels]
    DPO: List[DPO]
    EMA: List[EMA]
    EMV: List[EMV]
    ForceIndex: List[ForceIndex]
    HMA: List[HMA]
    Ichimoku: List[Ichimoku]
    KAMA: List[KAMA]
    KeltnerChannels: List[KeltnerChannels]
    KST: List[KST]
    KVO: List[KVO]
    MACD: List[MACD]
    MassIndex: List[MassIndex]
    McGinleyDynamic: List[McGinleyDynamic]
    MeanDev: List[MeanDev]
    OBV: List[OBV]
    ROC: List[ROC]
    RSI: List[RSI]
    ParabolicSAR: List[ParabolicSAR]
    SFX: List[SFX]
    SMA: List[SMA]
    SMMA: List[SMMA]
    SOBV: List[SOBV]
    STC: List[STC]
    StdDev: List[StdDev]
    Stoch: List[Stoch]
    StochRSI: List[StochRSI]
    SuperTrend: List[SuperTrend]
    T3: List[T3]
    TEMA: List[TEMA]
    TRIX: List[TRIX]
    TSI: List[TSI]
    TTM: List[TTM]
    UO: List[UO]
    VTX: List[VTX]
    VWAP: List[VWAP]
    VWMA: List[VWMA]
    WMA: List[WMA]
    ZLEMA: List[ZLEMA]
