FROM python:3.12-slim

WORKDIR /app

COPY Docker/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONPATH "${PYTHONPATH}:/app"

ENTRYPOINT [ "python", "main.py" ]